# Generated by Django 4.0.4 on 2022-07-10 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='cost_basis',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='share',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='total_shares',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profit_loss',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('symbol', models.CharField(max_length=200)),
                ('transaction_date', models.DateField()),
                ('share', models.FloatField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cost_basis', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='transaction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainpage.transaction'),
        ),
    ]
