# Generated by Django 4.0.4 on 2022-07-10 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_portfolio_avg_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.transaction'),
        ),
    ]
