# Generated by Django 4.0.4 on 2022-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_remove_portfolio_transaction_portfolio_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(max_length=200),
        ),
    ]
