# Generated by Django 4.0.4 on 2022-07-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_portfolio_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
