# Generated by Django 4.0.4 on 2022-07-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_portfolio_company_name_alter_portfolio_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
