# Generated by Django 4.0.4 on 2022-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_rename_tickersymbols_tickersymbols_tickersymbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profit_loss',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_shares',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='avg_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost_basis',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='share',
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
