# Generated by Django 4.0.4 on 2022-07-19 11:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_alter_transaction_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='avg_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cost_basis',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='avg_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost_basis',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
    ]
