# Generated by Django 4.0.4 on 2022-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_alter_portfolio_avg_price_alter_portfolio_cost_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
