# Generated by Django 4.0.4 on 2022-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_alter_portfolio_avg_price_alter_portfolio_cost_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_shares',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='share',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
