# Generated by Django 4.1 on 2022-09-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0021_alter_portfolio_total_shares_alter_transaction_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="avg_price",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="cost_basis",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="current_value",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="profit_loss",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="avg_price",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="cost_basis",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
